### ISSUE TITLE
Error: tar: Error is not recoverable: exiting now

### ISSUE THREAD

**Issue by s0kil** [netlify/netlify-lm-plugin#30]
I have tried initializing Netlify Large Media by doing `netlify lm:setup`, here is the error I get -

```bash
  ✔ Checking Git version [2.20.1]
  ✔ Checking Git LFS version [2.9.2]
  ✔ Checking Git LFS filters
  ✖ Installing Netlify's Git Credential Helper for Linux
    → tar: Error is not recoverable: exiting now
    Configuring Git to use Netlify's Git Credential Helper
Error: Command failed: tar -C /home/sokil/.netlify/helper/bin -xzf /tmp/netlify-Z8QrUT/git-credential-netlify-linux-amd64.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now


    at /home/sokil/.local/share/netlify-cli/node_modules/netlify-lm-plugin/node_modules/execa/index.js:231:11
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async extractFile (/home/sokil/.local/share/netlify-cli/node_modules/netlify-lm-plugin/lib/install.js:135:5)
    at async Task.task (/home/sokil/.local/share/netlify-cli/node_modules/netlify-lm-plugin/lib/install.js:73:13) {
  code: 2,
  killed: false,
  stdout: '',
  stderr: '\n' +
    'gzip: stdin: not in gzip format\n' +
    'tar: Child returned status 1\n' +
    'tar: Error is not recoverable: exiting now\n',
  failed: true,
  signal: null,
  cmd: 'tar -C /home/sokil/.netlify/helper/bin -xzf /tmp/netlify-Z8QrUT/git-credential-netlify-linux-amd64.tar.gz',
  timedOut: false,
  context: [Object: null prototype] {}
}
```

Netlify Version: `netlify-cli/2.30.0 linux-x64 node-v12.14.1`

**Comment by s0kil** [comment]
I have also tried it with latest Node version:
```bash
./node_modules/.bin/netlify version
netlify-cli/2.30.0 linux-x64 node-v13.6.0
```

**Comment by s0kil** [comment]
I have also tried installing `netlify-cli` and then calling:
- `./node_modules/.bin/netlify plugins:install netlify-lm-plugin`
- `./node_modules/.bin/netlify lm:install`

And the issue did not show up.
